import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-2 bg-gray-100 text-right flex gap-4 justify-end">
          <a href="/scenarios" className="text-blue-600 hover:underline text-sm">시나리오 선택</a>
          <a href="/history" className="text-blue-600 hover:underline text-sm">히스토리</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
